-- COD-63: Listing에 autoGenerated, ruleSnapshot 필드 추가

ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Listing" ADD COLUMN IF NOT EXISTS "ruleSnapshot" JSONB;
